apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openai-microservices-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hasithaprageeth/openai-microservices-configs
    targetRevision: main
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true