apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openai-microservices-stage
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hasithaprageeth/openai-microservices-configs
    targetRevision: main
    path: stage
  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  rolloutStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1