apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openai-microservices-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: openai-service-dev.com
    http:
      paths:
        - path: /chat
          pathType: Prefix
          backend:
            service:
              name: chat-service-svc
              port:
                number: 6061
        - path: /edit
          pathType: Prefix
          backend:
            service:
              name: edit-service-svc
              port:
                number: 6062
        - path: /completions
          pathType: Prefix
          backend:
            service:
              name: completions-service-svc
              port:
                number: 6063
        - path: /image
          pathType: Prefix
          backend:
            service:
              name: image-service-svc
              port:
                number: 6064