apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service-deployment
  labels:
    app: image-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: edit-service
          image: hasitha2021/image-service:stage-1.0
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-microservices-secrets
                  key: openai-api-key
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: openai-microservices-secrets
                  key: database_host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: openai-microservices-secrets
                  key: database_port
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: openai-microservices-secrets
                  key: database_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openai-microservices-secrets
                  key: database_pwd
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: openai-microservices-secrets
                  key: image_database
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-microservices-secrets
                  key: api-key

---
apiVersion: v1
kind: Service
metadata:
  name: image-service-svc
spec:
  type: ClusterIP
  selector:
    app: image-service
  ports:
  - port: 6164
    targetPort: 8000
    protocol: TCP